# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 11:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobcategory',
            options={'verbose_name_plural': 'JobCategories'},
        ),
    ]
