# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_userlogin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserLogin',
            new_name='UserCreate',
        ),
    ]
