# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20170320_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='experience',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='keyskills',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
