# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_auto_20170320_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='applied',
            field=models.ManyToManyField(blank=True, to='jobs.Job'),
        ),
    ]
