# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_remove_profile_applied'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_applied', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Job')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Profile')),
            ],
        ),
    ]
