# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 16:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_job_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_application',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
